spring:
  profiles:
    active: dev
  application:
    name: auth-server
    description: "authorization server"
  jackson:
    time-zone: "Asia/Seoul"

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
      base-path: /actuator
      path-mapping:
        health: health
