spring:
  profiles:
    active: local
  application:
    name: service-api
    description: "serviec Service api"
  jackson:
    time-zone: "Asia/Seoul"

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
      base-path: /actuator
      path-mapping:
        health: health


server:
  port: 9030

#security:
#  oauth2:
#    client:
#      client-id: renzo-client
#      client-secret: renzo-pass
#    resource:
#      token-info-uri: http://127.0.0.1:9020/oauth/check_token